name: simasndan
description: Aplikasi untuk ponpes al-muayyad windan.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bot_toast: ^4.0.4
  dio: ^5.2.1+1
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  flutter_svg: ^2.0.7
  geocoding: ^2.1.0
  geolocator: ^10.0.0
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.1
  intl: ^0.18.1
  permission_handler: ^10.4.3
  shimmer: ^3.0.0
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
